insert into station values
( 'Thiruvananthpuram Junction', 'TVC', 'Thiruvananthpuram' ),
( 'Kanyakumari Junction', 'CAPE', 'Kanyakumari' ),
( 'Madurai', 'MDU', 'Madurai' ),
( 'Palakkad Junction', 'PGT', 'Palakkad' ),
( 'Coimbatore Junction', 'CBE', 'Coimbatore' ),
( 'Erode Junction', 'ED', 'Erode' ),
( 'Tiruchchirapalli Junction', 'TPJ', 'Tiruchchirapalli' ),
( 'Chennai Central', 'MAS', 'Chennai' ),
( 'Vijayawada Junction', 'BZA', 'Vijayawada' ),
( 'Visakhapatnam', 'VSKP', 'Visakhapatnam' ),
( 'Bhubaneshwara Junction', 'BBS', 'Bhubaneshwara' ),
( 'Ranchi', 'RNC', 'Ranchi' ),
( 'Patna Junction', 'PNBE', 'Patna' ),
( 'Kolkata', 'KOAA', 'Kolkata' ),
( 'Bangalore Junction', 'BNC', 'Bangalore' ),
( 'Hyderabad', 'HYB', 'Hyderabad' ),
( 'Warangal', 'WL', 'Warangal' ),
( 'Nagpur Junction', 'NGP', 'Nagpur' ),
( 'Jalgaon', 'JL', 'Jalgaon' ),
( 'Chattrapati Shivaji Maharaj Terminus', 'CSTM', 'Mumbai' ),
( 'Pune', 'PUNE', 'Pune' ),
( 'Ahmedabad', 'ADI', 'Ahmedabad' ),
( 'Udaipur Junction', 'UDZ', 'Udaipur' ),
( 'Kota', 'KOTA', 'Kota' ),
( 'Jaipur', 'JP', 'Jaipur' ),
( 'Ujjain Junction', 'UJN', 'Ujjain' ),
( 'Bhopal Junction', 'BPL', 'Bhopal' ),
( 'Jhansi', 'JHS', 'Jhansi' ),
( 'New Delhi', 'NDLS', 'Delhi' ),
( 'Hazrat Nizamuddin', 'NZM', 'Delhi' ),
( 'Lucknow', 'LKO', 'Lucknow' ),
( 'Allahabad Junction', 'ALD', 'Allahabad' ),
( 'Varanasi Junction', 'BSB', 'Varanasi' );
